let Data = [
	{
		id: 1,
		inHome: 'y',
		type: ['newArrivals'],
		image: [
			'images/Products/product-1.jpg',
			'images/Products/product-3.jpg',
			'images/Products/product-1.jpg',
			'images/Products/product-3.jpg',
		],
		case: 'sale',
		title: 'Piqué Biker Jacket',
		size: ['all', 'xl', 'l'],
		category: ['all', 'clothes', 'men'],
		brand: ['all', 'chanel'],
		price: 67.25,
		productTotalPriceCart: '',
		tag: ['clothes'],
		rate: 3,
		qty: 0,
		liked: 'n',
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
	{
		id: 2,
		inHome: 'y',
		type: ['hotSales'],
		image: [
			'images/Products/product-2.jpg',
			'images/Products/product-4.jpg',
			'images/Products/product-2.jpg',
			'images/Products/product-4.jpg',
		],
		case: 'new',
		title: 'Multi-pocket Chest Bag',
		size: ['all', 'xl', 'l', 's'],
		category: ['all', 'clothes', 'woman'],
		brand: ['all', 'gucci'],
		price: 20,
		productTotalPriceCart: '',
		qty: 0,
		tag: ['clothes'],
		rate: 5,
		liked: 'n',
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
	{
		id: 3,
		inHome: 'y',
		type: ['newArrivals'],
		image: [
			'images/Products/product-4.jpg',
			'images/Products/product-2.jpg',
			'images/Products/product-4.jpg',
			'images/Products/product-2.jpg',
		],
		case: '',
		title: 'Lether Backpack',
		size: ['all', '2xl', '3xl'],
		category: ['all', 'clothing', 'kids', 'men'],
		tag: ['clothes'],
		brand: ['all', 'louis'],
		productTotalPriceCart: '',
		price: 17,
		qty: 0,
		rate: 4,
		liked: 'n',
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
	{
		id: 4,
		inHome: 'n',
		type: ['newArrivals'],
		image: [
			'images/Products/product-4.jpg',
			'images/Products/product-2.jpg',
			'images/Products/product-4.jpg',
			'images/Products/product-2.jpg',
		],
		case: '',
		title: 'Lether Backpack',
		tag: ['clothes'],
		size: ['all', '2xl', '3xl', 'm'],
		category: ['all', 'shoes', 'kids', 'men'],
		brand: ['all', 'hermes'],
		price: 17,
		productTotalPriceCart: '',
		qty: 0,
		liked: 'n',
		rate: 1,
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
	{
		id: 5,
		inHome: 'n',
		type: ['newArrivals'],
		image: [
			'images/Products/product-7.jpg',
			'images/Products/product-6.jpg',
			'images/Products/product-7.jpg',
			'images/Products/product-6.jpg',
		],
		case: '',
		title: 'Lether Backpack',
		tag: ['clothes'],
		size: ['all', '2xl', '3xl', 'm'],
		category: ['all', 'accessories'],
		brand: ['all', 'hermes'],
		rate: 5,
		price: 300,
		productTotalPriceCart: '',
		qty: 0,
		liked: 'n',
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
	{
		id: 6,
		inHome: 'y',
		type: ['hotSales'],
		image: [
			'images/Products/product-6.jpg',
			'images/Products/product-7.jpg',
			'images/Products/product-6.jpg',
			'images/Products/product-7.jpg',
		],
		case: 'new',
		tag: ['clothes'],
		title: 'Product Item',
		size: ['all', '2xl', '3xl', 'm'],
		category: ['all', 'bags'],
		productTotalPriceCart: '',
		brand: ['all', 'gucci'],
		price: 99.5,
		rate: 3,
		qty: 0,
		liked: 'n',
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
	{
		id: 7,
		inHome: 'y',
		type: ['newArrivals'],
		image: [
			'images/Products/product-5.jpg',
			'images/Products/product-8.jpg',
			'images/Products/product-5.jpg',
			'images/Products/product-8.jpg',
		],
		case: '',
		title: 'Product Item',
		size: ['all', '2xl', '3xl', 'm'],
		category: ['all', 'bags', 'woman', 'kids'],
		tag: ['clothes'],
		brand: ['all', 'gucci'],
		productTotalPriceCart: '',
		price: 80,
		qty: 0,
		rate: 4,
		liked: 'n',
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
	{
		id: 8,
		inHome: 'y',
		type: ['newArrivals'],
		image: [
			'images/Products/product-1.jpg',
			'images/Products/product-3.jpg',
			'images/Products/product-1.jpg',
			'images/Products/product-3.jpg',
		],
		case: 'sale',
		title: 'Piqué Biker Jacket',
		size: ['all', 'xl', 'l'],
		category: ['all', 'shoes', 'men'],
		brand: ['all', 'chanel'],
		price: 67.25,
		productTotalPriceCart: '',
		tag: ['clothes'],
		rate: 3,
		qty: 0,
		liked: 'n',
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
	{
		id: 9,
		inHome: 'n',
		type: ['newArrivals'],
		image: [
			'images/Products/product-2.jpg',
			'images/Products/product-4.jpg',
			'images/Products/product-2.jpg',
			'images/Products/product-4.jpg',
		],
		case: '',
		title: 'Multi-pocket Chest Bag',
		size: ['all', 'xl', 'l', 's'],
		category: ['all', 'accessories', 'woman'],
		brand: ['all', 'gucci'],
		price: 120.5,
		productTotalPriceCart: '',
		qty: 0,
		tag: ['clothes'],
		rate: 5,
		liked: 'n',
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
	{
		id: 10,
		inHome: 'y',
		type: ['hotSales'],
		image: [
			'images/Products/product-3.jpg',
			'images/Products/product-1.jpg',
			'images/Products/product-3.jpg',
			'images/Products/product-1.jpg',
		],
		case: '',
		title: 'Multi-pocket Chest Bag',
		size: ['all', 'xs', '3xl', 'l'],
		productTotalPriceCart: '',
		category: ['all', 'bags', 'woman', 'men'],
		tag: ['clothes'],
		brand: ['all', 'louis'],
		price: 56,
		rate: 3,
		qty: 0,
		liked: 'n',
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
	{
		id: 11,
		inHome: 'y',
		type: ['newArrivals'],
		image: [
			'images/Products/product-4.jpg',
			'images/Products/product-2.jpg',
			'images/Products/product-4.jpg',
			'images/Products/product-2.jpg',
		],
		case: 'sale',
		title: 'Lether Backpack',
		size: ['all', '2xl', '3xl'],
		category: ['all', 'clothing', 'kids', 'men'],
		tag: ['clothes'],
		brand: ['all', 'louis'],
		productTotalPriceCart: '',
		price: 9,
		qty: 0,
		rate: 4,
		liked: 'n',
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
	{
		id: 12,
		inHome: 'n',
		type: ['newArrivals'],
		image: [
			'images/Products/product-5.jpg',
			'images/Products/product-7.jpg',
			'images/Products/product-5.jpg',
			'images/Products/product-7.jpg',
		],
		case: '',
		title: 'Lether Backpack',
		tag: ['clothes'],
		size: ['all', '2xl', '3xl', 'm'],
		category: ['all', 'shoes', 'kids', 'men'],
		brand: ['all', 'hermes'],
		price: 75,
		productTotalPriceCart: '',
		qty: 0,
		liked: 'n',
		rate: 1,
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
	{
		id: 13,
		inHome: 'n',
		type: ['newArrivals'],
		image: [
			'images/Products/product-7.jpg',
			'images/Products/product-6.jpg',
			'images/Products/product-7.jpg',
			'images/Products/product-6.jpg',
		],
		case: 'sale',
		title: 'Lether Backpack',
		tag: ['clothes'],
		size: ['all', '2xl', '3xl', 'm'],
		category: ['all', 'accessories'],
		brand: ['all', 'hermes'],
		rate: 5,
		price: 300,
		productTotalPriceCart: '',
		qty: 0,
		liked: 'n',
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
	{
		id: 14,
		inHome: 'n',
		type: ['hotSales'],
		image: [
			'images/Products/product-6.jpg',
			'images/Products/product-7.jpg',
			'images/Products/product-6.jpg',
			'images/Products/product-7.jpg',
		],
		case: '',
		tag: ['clothes'],
		title: 'Product Item',
		size: ['all', '2xl', '3xl', 'm'],
		category: ['all', 'bags'],
		productTotalPriceCart: '',
		brand: ['all', 'gucci'],
		price: 15.5,
		rate: 3,
		qty: 0,
		liked: 'n',
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
	{
		id: 15,
		inHome: 'n',
		type: ['newArrivals'],
		image: [
			'images/Products/product-5.jpg',
			'images/Products/product-8.jpg',
			'images/Products/product-5.jpg',
			'images/Products/product-8.jpg',
		],
		case: 'new',
		title: 'Product Item',
		size: ['all', '2xl', '3xl', 'm'],
		category: ['all', 'bags', 'woman', 'kids'],
		tag: ['clothes'],
		brand: ['all', 'gucci'],
		productTotalPriceCart: '',
		price: 140.25,
		qty: 0,
		rate: 4,
		liked: 'n',
		desc: 'Coat with quilted lining and an adjustable hood. Featuring long sleeves with adjustable cuff tabs, adjustable asymmetric hem with elastic side tabs and a front zip fastening with placket.',
	},
];

let blogData = [
	{
		id: 1,
		date: '16 February 2020',
		title: 'What Curling Irons Are The Best Ones',
		image: 'images/Blog/blog-1.jpg.webp',
	},
	{
		id: 2,
		date: '20 February 2020',
		title: 'What Curling Irons Are The Best Ones',
		image: 'images/Blog/blog-2.jpg.webp',
	},
	{
		id: 3,
		date: '36 February 2020',
		title: 'What Curling Irons Are The Best Ones',
		image: 'images/Blog/blog-3.jpg.webp',
	},
	{
		id: 4,
		date: '40 February 4040',
		title: 'What Curling Irons Are The Best Ones',
		image: 'images/Blog/blog-4.jpg.webp',
	},
	{
		id: 5,
		date: '20 February 2020',
		title: 'What Curling Irons Are The Best Ones',
		image: 'images/Blog/blog-5.jpg.webp',
	},
	{
		id: 6,
		date: '26 February 2020',
		title: 'What Curling Irons Are The Best Ones',
		image: 'images/Blog/blog-6.jpg.webp',
	},
	{
		id: 7,
		date: '26 February 2020',
		title: 'What Curling Irons Are The Best Ones',
		image: 'images/Blog/blog-7.jpg.webp',
	},
	{
		id: 8,
		date: '28 February 2020',
		title: 'What Curling Irons Are The Best Ones',
		image: 'images/Blog/blog-8.jpg.webp',
	},
	{
		id: 9,
		date: '29 February 2020',
		title: 'What Curling Irons Are The Best Ones',
		image: 'images/Blog/blog-9.jpg.webp',
	},
];
